AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: createapplication/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /createapplication
            Method: get

Outputs:
  LoanApplicationApi:
    Description: "API Gateway endpoint URL for Prod stage for Submit loan function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/createapplication/"
  LoanApplicationFunction:
    Description: "Loan application Lambda Function ARN"
    Value: !GetAtt LoanApplicationFunction.Arn
  LoanApplicationFunctionIamRole:
    Description: "Implicit IAM Role created for Submit loan function"
    Value: !GetAtt LoanApplicationFunctionRole.Arn
