version = 0.1
[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "loan"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11okeji7zzwcw"
s3_prefix = "loan"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ParameterInstancePrefix=\"loan\""
image_repositories = []
