AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  createloanapplication

  Sample SAM Template for createloanapplication

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LoanApplicationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Loan_Application/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        LoanApplication:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /loanapplication
            Method: post
      Policies:
      # Give the Lambda service access to poll your DynamoDB Stream
        - AmazonDynamoDBFullAccess

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoanApplicationApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/loanapplication/"
  LoanApplicationFunction:
    Description: "LoanApplication Lambda Function ARN"
    Value: !GetAtt LoanApplicationFunction.Arn
  LoanApplicationFunctionIamRole:
    Description: "Implicit IAM Role created for LoanApplication function"
    Value: !GetAtt LoanApplicationFunctionRole.Arn
